"""
R-IDeA: Representativeness + Informativeness + De-amplification.

Standalone scoring module implementing Tang, Sloman & Kaski (2025).
Designed to be tested independently before integration into the main
experiment selection pipeline.

Three-objective acquisition function for Bayesian model comparison:
  1. Informativeness (EIG) — how much does this experiment reduce
     posterior uncertainty? (existing capability)
  2. Representativeness — how different is this experiment from
     previously executed ones? (prevents repetition)
  3. De-amplification — how balanced is this experiment's
     informativeness across models? (prevents model-type bias)

References:
    Tang, Y., Sloman, S. J., & Kaski, S. (2025). R-IDeA:
    Representativeness, informativeness, and de-amplification for
    Bayesian optimal experimental design under model misspecification.
    arXiv:2506.07805.
"""

from __future__ import annotations

from typing import Optional

import numpy as np

from antagonistic_collab.bayesian_selection import (
    ModelPosterior,
    compute_eig,
    compute_log_likelihood,
)


# ── Component Scores ──


def compute_representativeness(
    model_predictions: dict[str, np.ndarray],
    previous_predictions: list[dict[str, np.ndarray]],
) -> float:
    """How different is this candidate from previously executed experiments?

    Measured as minimum Euclidean distance in prediction space to any
    prior experiment. If no prior experiments, returns 1.0 (maximally
    representative).

    Args:
        model_predictions: {model_name: array of P(correct) per item}
            for the candidate experiment.
        previous_predictions: list of prediction dicts from prior
            experiments (same format as model_predictions).

    Returns:
        Non-negative float. Higher = more representative (more novel).
    """
    if not previous_predictions:
        return 1.0

    # Stack predictions into a single vector (sorted by model name for
    # consistency)
    sorted_names = sorted(model_predictions.keys())
    current = np.concatenate(
        [np.asarray(model_predictions[m], dtype=np.float64) for m in sorted_names]
    )

    min_dist = float("inf")
    for prev in previous_predictions:
        prev_vec = np.concatenate(
            [np.asarray(prev[m], dtype=np.float64) for m in sorted_names]
        )
        dist = float(np.linalg.norm(current - prev_vec))
        min_dist = min(min_dist, dist)

    return min_dist


def compute_deamplification(
    model_predictions: dict[str, np.ndarray],
    posterior: ModelPosterior,
    n_subjects: int = 20,
    n_sim: int = 200,
    seed: Optional[int] = 42,
    learning_rate: float = 1.0,
) -> float:
    """How balanced is this experiment's informativeness across models?

    Decomposes EIG by ground-truth model: for each model as hypothetical
    ground truth, compute the expected posterior entropy reduction. An
    experiment that is informative for ALL possible ground truths (not
    just the current posterior leader) has high de-amplification.

    Returns the minimum per-model information contribution (minimax
    fairness criterion). Higher = more balanced = less amplifying.

    Args:
        model_predictions: {model_name: array of P(correct) per item}
        posterior: current ModelPosterior
        n_subjects: simulated subjects per item
        n_sim: Monte Carlo simulations per model
        seed: random seed
        learning_rate: likelihood tempering parameter

    Returns:
        Non-negative float. Higher = more balanced informativeness.
    """
    rng = np.random.default_rng(seed)

    h_current = posterior.entropy
    model_names = posterior.model_names
    n_models = len(model_names)
    priors = posterior.probs

    # Collect prediction arrays in model-name order
    pred_arrays = []
    for name in model_names:
        p = np.asarray(model_predictions[name], dtype=np.float64)
        p = np.clip(p, 0.05, 0.95)
        pred_arrays.append(p)

    n_items = len(pred_arrays[0])

    # Per-model information contribution: how much posterior entropy
    # decreases when data is generated by model_i
    per_model_info = []
    for gt_idx in range(n_models):
        if priors[gt_idx] < 1e-10:
            per_model_info.append(0.0)
            continue

        gt_preds = pred_arrays[gt_idx]

        # Simulate datasets from this ground truth
        sim_correct = rng.binomial(n_subjects, gt_preds, size=(n_sim, n_items))
        sim_observed = sim_correct / n_subjects

        entropies = np.zeros(n_sim)
        for s in range(n_sim):
            obs = sim_observed[s]
            lls = np.zeros(n_models)
            for m_idx in range(n_models):
                lls[m_idx] = compute_log_likelihood(obs, pred_arrays[m_idx], n_subjects)
            new_lp = posterior.log_probs + learning_rate * lls
            new_lp = new_lp - np.max(new_lp)
            new_p = np.exp(new_lp)
            new_p = new_p / new_p.sum()
            entropies[s] = -np.sum(new_p * np.log(new_p + 1e-30))

        # Information contribution = entropy reduction when this model
        # is the ground truth
        info_i = h_current - float(np.mean(entropies))
        per_model_info.append(max(0.0, info_i))

    # Minimax: return the minimum per-model contribution.
    # An experiment that is informative for all models scores high.
    # An experiment only informative for one model scores low.
    if not per_model_info:
        return 0.0
    return min(per_model_info)


# ── Combined Scoring ──


def _normalize_scores(scores: list[float]) -> list[float]:
    """Min-max normalize to [0, 1]. If all equal, return uniform 0.5."""
    arr = np.array(scores, dtype=np.float64)
    lo, hi = arr.min(), arr.max()
    if hi - lo < 1e-15:
        return [0.5] * len(scores)
    return ((arr - lo) / (hi - lo)).tolist()


def compute_ridea_scores(
    pool_predictions: list[dict[str, np.ndarray]],
    posterior: ModelPosterior,
    previous_predictions: list[dict[str, np.ndarray]],
    alpha: float = 0.3,
    beta: float = 0.3,
    n_subjects: int = 20,
    n_sim: int = 200,
    seed: Optional[int] = 42,
    learning_rate: float = 1.0,
) -> list[float]:
    """Score a pool of candidates using R-IDeA.

    Computes three components for each candidate, normalizes each to
    [0, 1], then combines with weights:
        score = gamma * informativeness + alpha * representativeness
                + beta * de-amplification
    where gamma = 1 - alpha - beta.

    Args:
        pool_predictions: list of prediction dicts, one per candidate.
            Each dict maps model_name → P(correct) array.
        posterior: current ModelPosterior
        previous_predictions: prediction dicts from prior experiments
        alpha: weight for representativeness [0, 1]
        beta: weight for de-amplification [0, 1]
        n_subjects: simulated subjects per item
        n_sim: Monte Carlo simulations per model
        seed: random seed
        learning_rate: likelihood tempering parameter

    Returns:
        List of non-negative R-IDeA scores, one per candidate.
    """
    if alpha + beta > 1.0:
        raise ValueError(f"alpha + beta must be <= 1.0, got {alpha + beta}")

    gamma = 1.0 - alpha - beta

    # Compute raw scores for each component
    eig_raw = []
    rep_raw = []
    deamp_raw = []

    for i, preds in enumerate(pool_predictions):
        # Use different seed offsets per candidate for Monte Carlo variance
        cand_seed = seed + i if seed is not None else None

        eig_raw.append(
            compute_eig(preds, posterior, n_subjects, n_sim, cand_seed, learning_rate)
        )
        rep_raw.append(compute_representativeness(preds, previous_predictions))
        deamp_raw.append(
            compute_deamplification(
                preds, posterior, n_subjects, n_sim, cand_seed, learning_rate
            )
        )

    # Normalize each component to [0, 1]
    eig_norm = _normalize_scores(eig_raw)
    rep_norm = _normalize_scores(rep_raw)
    deamp_norm = _normalize_scores(deamp_raw)

    # Combine
    combined = [
        gamma * e + alpha * r + beta * d
        for e, r, d in zip(eig_norm, rep_norm, deamp_norm)
    ]

    return combined


# ── Selection ──


def select_ridea(
    pool_predictions: list[dict[str, np.ndarray]],
    posterior: ModelPosterior,
    previous_predictions: list[dict[str, np.ndarray]],
    strategy: str = "thompson",
    alpha: float = 0.3,
    beta: float = 0.3,
    n_subjects: int = 20,
    n_sim: int = 200,
    seed: Optional[int] = 42,
    learning_rate: float = 1.0,
) -> tuple[int, list[float]]:
    """Score pool with R-IDeA and select one candidate.

    Args:
        pool_predictions: list of prediction dicts, one per candidate
        posterior: current ModelPosterior
        previous_predictions: prediction dicts from prior experiments
        strategy: "greedy" (argmax) or "thompson" (proportional sampling)
        alpha: weight for representativeness
        beta: weight for de-amplification
        n_subjects, n_sim, seed, learning_rate: passed to scoring

    Returns:
        (selected_index, all_scores)
    """
    scores = compute_ridea_scores(
        pool_predictions,
        posterior,
        previous_predictions,
        alpha=alpha,
        beta=beta,
        n_subjects=n_subjects,
        n_sim=n_sim,
        seed=seed,
        learning_rate=learning_rate,
    )

    if strategy == "greedy":
        idx = int(np.argmax(scores))
    elif strategy == "thompson":
        rng = np.random.default_rng(seed)
        arr = np.array(scores, dtype=np.float64)
        total = arr.sum()
        if total <= 0:
            idx = int(rng.integers(len(scores)))
        else:
            weights = arr / total
            idx = int(rng.choice(len(scores), p=weights))
    else:
        raise ValueError(f"Unknown strategy: {strategy!r}")

    return idx, scores
